on: [push]

jobs:
  obs_helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload To Huawei OBS
        uses: ./
        id: upload_file_to_obs
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: cn-north-4
          bucket_name: hdn-github-action
          local_file_path: README.md
          operation_type: upload
      - name: List files in the repository
        run: |
          ls -al ${{ github.workspace }}
      - name: Download from Huawei OBS
        uses: ./
        id: download_file_from_obs
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          
          region: cn-north-4
          bucket_name: hdn-github-action
          local_file_path: ${{ github.workspace }}
          obs_file_path: test1.txt
          operation_type: download
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
